In [26]:
import math
import numpy as np
import pandas as pd

In [27]:
def Biseccion(f,a,b,tol,maxiter):
    iters = 0
    error = tol+1

    while error>tol and iters<=maxiter:
        x = (a+b)/2
        error = (b-a)/2
        if f(a)*f(x)>0:
            a = x
        else:
            b = x
        iters = iters+1

    return [x,iters,error]

In [28]:
def Bisecciontabla(f,a,b,tol,maxiter):
    iters = 0
    error = tol+1
    lista_a = list(); lista_b = list()
    lista_a.append(a); lista_b.append(b);
    lista_x = list(); lista_e = list()

    while error>tol and iters<=maxiter:
        x = (a+b)/2
        error = (b-a)/2
        lista_e.append(error); lista_x.append(x)
        if f(a)*f(x)>0:
            a = x
        else:
            b = x
        iters = iters+1
        lista_a.append(a); lista_b.append(b);
    lista_a.pop(); lista_b.pop()
    tabla = pd.DataFrame({'a': lista_a, 'b': lista_b, 'x': lista_x, 'Errores': lista_e})
    pd.set_option('display.precision', 10)
    return tabla

$$ f(x) = x^2 - 100xsin(x)+(10sin(x))^2$$

Resuelve las ecuaciones $$f(x) = 0$$ $$f'(x) = 0$$ en el intervalo [2.1,3.2] y [-3,-2] respectivamente con una tolerancia de $$10^{-3}$$

Escribir las tablas de resultados obtenidas

### Definición de $f(x)$ y su derivada
---
$$ f(x) = x^2 - 100x\sin(x)+(10\sin(x))^2$$
---
$$f'(x) = 2x - 100\sin(x) - 100x\cos(x) + 200\sin(x)\cos(x)$$

In [29]:
f = lambda x: x**2 - 100*x*math.sin(x) + (10*math.sin(x))**2
df = lambda x: 2*x - 100*math.sin(x) - 100*x*math.cos(x) + 200*math.sin(x)*math.cos(x)

### $f(x) = 0$ en $[2.1, 3.2]$

In [30]:
Bisecciontabla(f, 2.1, 3.2, 1e-3, 30)

              a             b             x       Errores
0   2.100000000  3.2000000000  2.6500000000  0.5500000000
1   2.650000000  3.2000000000  2.9250000000  0.2750000000
2   2.925000000  3.2000000000  3.0625000000  0.1375000000
3   3.062500000  3.2000000000  3.1312500000  0.0687500000
4   3.062500000  3.1312500000  3.0968750000  0.0343750000
5   3.096875000  3.1312500000  3.1140625000  0.0171875000
6   3.096875000  3.1140625000  3.1054687500  0.0085937500
7   3.105468750  3.1140625000  3.1097656250  0.0042968750
8   3.109765625  3.1140625000  3.1119140625  0.0021484375
9   3.109765625  3.1119140625  3.1108398438  0.0010742188
10  3.109765625  3.1108398438  3.1103027344  0.0005371094

### $f'(x) = 0$ en $[-3, -2]$

In [31]:
Bisecciontabla(df, -3, -2, 1e-3, 30)

            a            b             x       Errores
0 -3.00000000 -2.000000000 -2.5000000000  0.5000000000
1 -2.50000000 -2.000000000 -2.2500000000  0.2500000000
2 -2.50000000 -2.250000000 -2.3750000000  0.1250000000
3 -2.37500000 -2.250000000 -2.3125000000  0.0625000000
4 -2.37500000 -2.312500000 -2.3437500000  0.0312500000
5 -2.37500000 -2.343750000 -2.3593750000  0.0156250000
6 -2.35937500 -2.343750000 -2.3515625000  0.0078125000
7 -2.35937500 -2.351562500 -2.3554687500  0.0039062500
8 -2.35546875 -2.351562500 -2.3535156250  0.0019531250
9 -2.35546875 -2.353515625 -2.3544921875  0.0009765625