In [32]:
import math
import numpy as np
import pandas as pd

In [33]:
def Biseccion(f,a,b,tol,maxiter):
    iters = 0
    error = tol+1

    while error>tol and iters<=maxiter:
        x = (a+b)/2
        error = (b-a)/2
        if f(a)*f(x)>0:
            a = x
        else:
            b = x
        iters = iters+1

    return [x,iters,error]

In [34]:
def Bisecciontabla(f,a,b,tol,maxiter):
    iters = 0
    error = tol+1
    lista_a = list(); lista_b = list()
    lista_a.append(a); lista_b.append(b);
    lista_x = list(); lista_e = list()

    while error>tol and iters<=maxiter:
        x = (a+b)/2
        error = (b-a)/2
        lista_e.append(error); lista_x.append(x)
        if f(a)*f(x)>0:
            a = x
        else:
            b = x
        iters = iters+1
        lista_a.append(a); lista_b.append(b);
    lista_a.pop(); lista_b.pop()
    tabla = pd.DataFrame({'a': lista_a, 'b': lista_b, 'x': lista_x, 'Errores': lista_e})
    pd.set_option('display.precision', 2)
    return tabla

$$ f(x) = x^2 - 100xsin(x)+(10sin(x))^2$$

Resuelve las ecuaciones $$f(x) = 0$$ $$f'(x) = 0$$ en el intervalo [2.1,3.2] y [-3,-2] respectivamente con una tolerancia de $$10^{-3}$$

Escribir las tablas de resultados obtenidas

### Definición de $f(x)$ y su derivada
---
$$ f(x) = x^2 - 100x\sin(x)+(10\sin(x))^2$$
---
$$f'(x) = 2x - 100\sin(x) - 100x\cos(x) + 200\sin(x)\cos(x)$$

In [35]:
f = lambda x: x**2 - 100*x*math.sin(x) + (10*math.sin(x))**2
df = lambda x: 2*x - 100*math.sin(x) - 100*x*math.cos(x) + 200*math.sin(x)*math.cos(x)

### $f(x) = 0$ en $[2.1, 3.2]$

In [36]:
Bisecciontabla(f, 2.1, 3.2, 1e-3, 30)

       a     b     x   Errores
0   2.10  3.20  2.65  5.50e-01
1   2.65  3.20  2.93  2.75e-01
2   2.93  3.20  3.06  1.37e-01
3   3.06  3.20  3.13  6.88e-02
4   3.06  3.13  3.10  3.44e-02
5   3.10  3.13  3.11  1.72e-02
6   3.10  3.11  3.11  8.59e-03
7   3.11  3.11  3.11  4.30e-03
8   3.11  3.11  3.11  2.15e-03
9   3.11  3.11  3.11  1.07e-03
10  3.11  3.11  3.11  5.37e-04

### $f'(x) = 0$ en $[-3, -2]$

In [37]:
Bisecciontabla(df, -3, -2, 1e-3, 30)

      a     b     x   Errores
0 -3.00 -2.00 -2.50  5.00e-01
1 -2.50 -2.00 -2.25  2.50e-01
2 -2.50 -2.25 -2.38  1.25e-01
3 -2.38 -2.25 -2.31  6.25e-02
4 -2.38 -2.31 -2.34  3.12e-02
5 -2.38 -2.34 -2.36  1.56e-02
6 -2.36 -2.34 -2.35  7.81e-03
7 -2.36 -2.35 -2.36  3.91e-03
8 -2.36 -2.35 -2.35  1.95e-03
9 -2.36 -2.35 -2.35  9.77e-04