<table style="width:100%; font-size:11pt; border-collapse:collapse">
    <tr>
        <td colspan="2"
            style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   text-align:center;
                   font-weight:bold;
                   padding:8px;">
            Universidad de Oriente
        </td>
    </tr>
    <tr>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
                            Métodos Numéricos
        </td>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
            Clase 25 - Método de Newton - Sistemas No Lineales 
        </td>
    </tr>
    <tr>
 

</table>

# Método de Newton para sistemas de ecuaciones no lineales

In [64]:
import math
import numpy as np
import pandas as pd

## Función que implementa el método de Newton

In [65]:
def NewtonSis(F,JF,x0,tol,maxiter):
    iters = 0
    error = tol + 1
    
    while iters<=maxiter and error > tol:
        z = np.linalg.solve(JF(x0), F(x0))
        x = x0 - z
        error = np.linalg.norm(x-x0)
        iters += 1
        x0 = x
    return [x,iters,error]

## Función que muestra la tabla del método de Newton

In [66]:
def NewtonSisTabla(F,JF,x0,tol,maxiter):
    iters = 0 #Contador de iteraciones a cero
    error = tol+1
    lista_error = list()
    lista_x = list()
    while error>tol and iters<=maxiter:
        z = np.linalg.solve(JF(x0),F(x0)) #Se resuelve el sistema lineal
        x = x0-z
        lista_x.append(x)
        error = np.linalg.norm(x-x0) #Se encuentra el error con la norma
        lista_error.append(error)
        x0 = x
        iters = iters+1
    Tabla = pd.DataFrame()
    Tabla["x"] = [w[0] for w in lista_x]
    Tabla["y"] = [w[1] for w in lista_x]
    Tabla["Errores"] = lista_error
    pd.set_option('display.precision', 16)
    return Tabla

### Ejemplo 1

Encontrar la solución al sistemas de ecuaciones
\begin{align*}
x^2+xy-10&=0 \\
y+3xy^2-57&=0
\end{align*}

Con el método de Newton usando las estimaciones iniciales $x_0=1.5$ e $y_0=3.5$ y una tolerancia de $10^{-8}$

In [67]:
def F(w):
    x,y = w
    S = np.zeros(2)
    S[0] = x**2+x*y-10
    S[1] = y+3*x*y**2-57
    # print(S.shape)
    return S

def JF(w):
    x, y = w
    M = np.zeros([2,2])
    M[0,0] = 2*x+y
    M[0,1] = x
    M[1,0] = 3*y**2
    M[1,1] = 1+6*x*y
    return M

tol = 1e-8
x0 = np.array([1.5,3.5])
maxiter = 30

In [68]:
x, iters, error = NewtonSis(F,JF,x0,tol,maxiter)

print(f"La solición al sistema es {x}")
print(f"El error obtenido fue de {error}")
print(f"Las iteraciones realizadas fueron {iters}")

La solición al sistema es [2. 3.]
El error obtenido fue de 7.717990670589357e-14
Las iteraciones realizadas fueron 5

In [69]:
NewtonSisTabla(F,JF,x0,tol,maxiter)

                    x                   y             Errores
0  2.0360288230584467  2.8438751000800639  0.8472465895147467
1  1.9987006090558244  3.0022885629245080  0.1627520223253573
2  1.9999999838762601  2.9999994133889132  0.0026322196945347
3  1.9999999999999800  3.0000000000000751  0.0000005868327100
4  1.9999999999999998  3.0000000000000004  0.0000000000000772

## Ejemplo 2

Resolver el siguiente sistema no lineal
\begin{align*}
4x^2-20x+\frac{1}{4}y^2+8 &=0 \\
\dfrac{1}{2}xy^2+2x-5y+8&=0
\end{align*}
Con una tolerancia de $10^{-6}$ y una estimación inicial de $\mathbf{x}^{(0)}=(0,0)$

In [70]:
# Sistema no lineal 
def F(w):
    x,y = w
    S = np.zeros(2)
    S[0] = 4*x**2-20*x+1/4*y**2+8
    S[1] = 1/2*x*y**2+2*x-5*y+8
    return S

def JF(w):
    x,y = w
    M = np.zeros([2,2])
    M[0,0] = 8*x-20; M[0,1] = 1/2*y
    M[1,0] = 1/2*y**2; M[1,1] = x*y-5
    return M

tol = 1e-6
x0 = np.array([0,0])
maxiter = 30

x,iters, error = NewtonSis(F,JF,x0,tol,maxiter)

print(f"La solición al sistema es {x}")
print(f"El error obtenido fue de {error}")
print(f"Las iteraciones realizadas fueron {iters}")

La solición al sistema es [0.5        1.99999999]
El error obtenido fue de 2.1053569892718102e-07
Las iteraciones realizadas fueron 7

In [71]:
NewtonSisTabla(F,JF,x0,tol,maxiter)

                    x                   y             Errores
0  0.4000000000000000  1.6000000000000001  1.6492422502470643
1  0.4918032786885247  1.9278688524590166  0.3404788192982866
2  0.4996127586646462  1.9951741700046153  0.0677568723260697
3  0.4999869864951915  1.9997976774030948  0.0046386277208835
4  0.4999995793188240  1.9999932792885247  0.0001960068284289
5  0.4999999864286597  1.9999997828697789  0.0000065163108849
6  0.4999999995622139  1.9999999929954324  0.0000002105356989

## Ejemplo 3

Aproximar la solución del sistema no lineal
\begin{align*}
f(x,y)&=e^xe^y+x \cos (y) \\
g(x,y)&=x+y-1
\end{align*}
Con una tolerancia de $10^{-7}$ y una estimación inicial de $\mathbf{x}^{(0)}=(2,1)$