<table style="width:100%; font-size:11pt; border-collapse:collapse">
    <tr>
        <td colspan="2"
            style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   text-align:center;
                   font-weight:bold;
                   padding:8px;">
            Universidad de Oriente
        </td>
    </tr>
    <tr>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
                            Métodos Numéricos
        </td>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
            Clase 23 - Método de Jarrat y CMT
        </td>
    </tr>
    <tr>
 

</table>

In [3]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Función que implementa el método de Jarrat

In [4]:
def Jarrat(f,df,x0,tol,maxiter):
    
    iters = 0
    error = tol+1
    error_x = list()

    while error>tol and iters<=maxiter:

        y = x0-2/3*f(x0)/df(x0)
        x = x0-(3*df(y)+df(x0))/(6*df(y)-2*df(x0))*f(x0)/df(x0)
        error = math.fabs(x-x0)
        error_x.append(error)
        iters = iters+1
        x0 = x

    error_x = np.array(error_x)
    ACOC = np.log(error_x[2:]/error_x[1:-1])/np.log(error_x[1:-1]/error_x[0:-2])
    
    return [x,iters,error,ACOC]

## Ejemplo 1:

Resolver la ecuación $x^2+\sin(x)+x=0$ usando el método de Jarrat, con una estimación inicial de $x_0=2$ y un tolerancia de $10^{-8}$.

In [5]:
#Introducir f
f = lambda x: x**2+math.sin(x)+x

#Introducir la derivada
df = lambda x: 2*x+math.cos(x)+1
x0 = 2
tol = 1e-8
maxiter = 30

x,iters,error,ACOC = Jarrat(f,df,x0,tol,maxiter)

print("El valor de la solución es de x = %s" %x)
print("El número de iteraciones realizadas es de %s" %iters)
print("El error cometido fue %s" %error)
print("Los resultados del ACOC son %s" %ACOC)

El valor de la solución es de x = 0.0
El número de iteraciones realizadas es de 4
El error cometido fue 1.6940658945086007e-21
Los resultados del ACOC son [3.03732978 4.06380699]

## Función que muestra los resultados en forma de tabla

In [6]:
def JarratTabla(f,df,x0,tol,maxiter):
    iters = 0
    error = tol+1
    lista_e = list(); lista_x = list()
    
    while error>tol and iters<=maxiter:
        y = x0-2/3*f(x0)/df(x0)
        x = x0-(3*df(y)+df(x0))/(6*df(y)-2*df(x0))*f(x0)/df(x0)
        error = math.fabs(x-x0)
        iters = iters+1
        lista_e.append(error)
        lista_x.append(x)
        x0 = x
    Tabla = pd.DataFrame({"Iteraciones": lista_x, "Errores": lista_e})
    pd.set_option('display.precision', 16)
    return Tabla

JarratTabla(f,df,x0,tol,maxiter)

## Ejemplo 2:

Resolver la ecuación $\sqrt{x}-\cos(x)=0$ usando el método de Jarrat, con una estimación inicial de $x_0=2.5$ y un tolerancia de $10^{-8}$.

In [7]:
#Introducir f
f = lambda x: math.sqrt(x)-math.cos(x)

#Introducir la derivada
df = lambda x: 1/2*x**(-1/2)+math.sin(x)
x0 = 2.5
tol = 1e-8
maxiter = 30

x,iters,error,ACOC = Jarrat(f,df,x0,tol,maxiter)

print("El valor de la solución es de x = %s" %x)
print("El número de iteraciones realizadas es de %s" %iters)
print("El error cometido fue %s" %error)
print("Los resultados del ACOC son %s" %ACOC)

El valor de la solución es de x = 0.6417143708728827
El número de iteraciones realizadas es de 4
El error cometido fue 2.220446049250313e-16
Los resultados del ACOC son [3.30478422 4.10563696]

In [8]:
JarratTabla(f,df,x0,tol,maxiter)

          Iteraciones             Errores
0  0.3696047932552418  2.1303952067447582
1  0.6414129784966738  0.2718081852414320
2  0.6417143708728825  0.0003013923762087
3  0.6417143708728827  0.0000000000000002

## Ejemplo 3

Encontrar la solución estimada a la ecuación $(x+2)e^{x}-1=0$ empleando el método de Jarrat con una tolerancia de $10^{-7}$ y una estimación inicial $x_0=-1$

In [9]:
#Introducir f
f = lambda x: (x+2)*math.exp(x)-1

#Introducir la derivada
df = lambda x: (x+2)*math.exp(x)+ math.exp(x)
x0 = -1
tol = 1e-7
maxiter = 30

x,iters,error,ACOC = Jarrat(f,df,x0,tol,maxiter)

print("El valor de la solución es de x = %s" %x)
print("El número de iteraciones realizadas es de %s" %iters)
print("El error cometido fue %s" %error)
print("Los resultados del ACOC son %s" %ACOC)

El valor de la solución es de x = -0.4428544010023886
El número de iteraciones realizadas es de 3
El error cometido fue 1.9825666996986513e-08
Los resultados del ACOC son [4.0717806]

In [10]:
JarratTabla(f,df,x0,tol,maxiter)

          Iteraciones             Errores
0 -0.4233882850914167  0.5766117149085833
1 -0.4428543811767216  0.0194660960853049
2 -0.4428544010023886  0.0000000198256670

## Función que implementa el método de CMT

In [ ]:
import mpmath as mp

mp.mp.dps = 100

def CMT(f,df,x0,tol,maxiter):
    
    iters = 0
    error = tol+1
    error_x = list()

    while error>tol and iters<=maxiter:

        y = x0-f(x0)/df(x0) #Newton
        z = y-f(x0)/(f(x0)-2*f(y))*f(y)/df(x0) #Ostrowki
        x = z-(1+2*f(y)/f(x0))*f(z)/df(x0)
        error = math.fabs(x-x0)
        error_x.append(error)
        iters = iters+1
        x0 = x

    error_x = np.array(error_x)
    ACOC = np.log(error_x[2:]/error_x[1:-1])/np.log(error_x[1:-1]/error_x[0:-2])
    
    return [x,iters,error,ACOC]

## Función que muestra los resultados en forma de tabla

In [12]:
def CMTTabla(f,df,x0,tol,maxiter):
    iters = 0
    error = tol+1
    lista_e = list(); lista_x = list()
    
    while error>tol and iters<=maxiter:
        y = x0-f(x0)/df(x0)
        z = y-f(x0)/(f(x0)-2*f(y))*f(y)/df(x0)
        x = z-(1+2*f(y)/f(x0))*f(z)/df(x0)
        error = math.fabs(x-x0)
        iters = iters+1
        lista_e.append(error)
        lista_x.append(x)
        x0 = x
    Tabla = pd.DataFrame({"Iteraciones": lista_x, "Errores": lista_e})
    pd.set_option('display.precision', 16)
    return Tabla

## Ejemplo 4

Encontrar la solución estimada a la ecuación $(x+2)e^{x}-1=$ empleando el método CMT con una tolerancia de $10^{-10}$ y una estimación inicial $x_0=-1$

In [13]:
#Introducir f
f = lambda x: (x+2)*math.exp(x)-1

#Introducir la derivada
df = lambda x: (x+2)*math.exp(x)+ math.exp(x)
x0 = mp.mpf('-1')
#x0 = -1
tol = mp.mpf('1e-10')
#tol = 1e-10
maxiter = 30

x,iters,error,ACOC = CMT(f,df,x0,tol,maxiter)

print("El valor de la solución es de x = %s" %round(x,16))
print("El número de iteraciones realizadas es de %s" %iters)
print("El error cometido fue %s" %error)
print("Los resultados del ACOC son %s" %ACOC)

El valor de la solución es de x = -0.4428544010023886
El número de iteraciones realizadas es de 4
El error cometido fue 2.0123767195560316e-17
Los resultados del ACOC son [6.54589839 1.29161469]

In [14]:
CMTTabla(f,df,x0,tol,maxiter)

                                         Iteraciones                 Errores
0  -0.3855436871671145417590324149452063155264412...  6.1445631283288549e-01
1  -0.4428543906678896891482031173395329075999337...  5.7310703500775148e-02
2  -0.4428544010023886061227225638047910531256462...  1.0334498916974519e-08
3  -0.4428544010023886262464897593651075383595381...  2.0123767195560316e-17

## Ejemplo 5

Encontrar la solución estimada a la ecuación $\cos(x)-xe^x+x^2=0$ empleando el método CMT con una tolerancia de $10^{-10}$ y una estimación inicial $x_0=2$

In [15]:
#Introducir f
f = lambda x: math.cos(x)-x*math.exp(x)+x**2

#Introducir la derivada
df = lambda x: -math.sin(x)-x*math.exp(x)-math.exp(x)+2*x
x0 = mp.mpf('2')
tol = mp.mpf('1e-10')
maxiter = 30

x,iters,error,ACOC = CMT(f,df,x0,tol,maxiter)

print("El valor de la solución es de x = %s" %round(x,16))
print("El número de iteraciones realizadas es de %s" %iters)
print("El error cometido fue %s" %error)
print("Los resultados del ACOC son %s" %ACOC)

El valor de la solución es de x = 0.6391540963320075
El número de iteraciones realizadas es de 4
El error cometido fue 8.39691348469301e-18
Los resultados del ACOC son [5.09526999 2.74130409]

In [16]:
CMTTabla(f,df,x0,tol,maxiter)

                                         Iteraciones                 Errores
0  0.80591686656690827373322554486192678408978424...  1.1940831334330917e+00
1  0.63916143902782450204119995058218415989231560...  1.6675542753908376e-01
2  0.63915409633200755720384871168260182243188691...  7.3426958169448374e-06
3  0.63915409633200754880693522698959254557483435...  8.3969134846930100e-18

## Ejemplo 6

Encontrar la solución estimada a la ecuación $\sqrt{x^2+2x+5}-2 \sin(x)-x^2+3=0$ empleando el método CMT con una tolerancia de $10^{-12}$ y una estimación inicial $x_0=3$

In [17]:
#Introducir f
f = lambda x: math.sqrt(x**2+2*x+5)-2*math.sin(x)-x**2+3

#Introducir la derivada
df = lambda x: 1/2*(x**2+2*x+5)**(-1/2)*(2*x+2)-2*math.cos(x)-2*x
x0 = mp.mpf('3')
tol = mp.mpf('1e-12')
maxiter = 30

x,iters,error,ACOC = CMT(f,df,x0,tol,maxiter)

print("El valor de la solución es de x = %s" %round(x,16))
print("El número de iteraciones realizadas es de %s" %iters)
print("El error cometido fue %s" %error)
print("Los resultados del ACOC son %s" %ACOC)

El valor de la solución es de x = 2.3319676558839638
El número de iteraciones realizadas es de 3
El error cometido fue 1.1573370117022265e-16
Los resultados del ACOC son [3.1511291]

In [18]:
CMTTabla(f,df,x0,tol,maxiter)

                                         Iteraciones             Errores
0  2.33186100352589145196371165349188392177576466...  0.6681389964741086
1  2.33196765588396391954344965924128826138000169...  0.0001066523580725
2  2.33196765588396380380974848901863248663749957...  0.0000000000000001