<table style="width:100%; font-size:11pt; border-collapse:collapse">
    <tr>
        <td colspan="2"
            style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   text-align:center;
                   font-weight:bold;
                   padding:8px;">
            Universidad de Oriente
        </td>
    </tr>
    <tr>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
                            Métodos Numéricos
        </td>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
            Clase 19 - Método de Newton
        </td>
    </tr>
    <tr>
 

</table>

In [17]:
import math
import pandas as pd

## Función del método de Newton

In [18]:
def Newton(f,df,x0,tol,maxiter):
    iters = 0
    error = tol+1

    while error>tol and iters<=maxiter:
        x = x0-f(x0)/df(x0)
        error = math.fabs(x-x0)
        iters = iters+1
        x0 = x
    return [x, iters, error]

## Función que brinda la tabla con todas las iteraciones

In [19]:
def NewtonTabla(f,df,x0,tol,maxiter):
    iters = 0
    error = tol+1
    lista_e = list(); lista_x = list()
    
    while error>tol and iters<=maxiter:
        x = x0-f(x0)/df(x0)
        error = math.fabs(x-x0)
        iters = iters+1
        lista_e.append(error)
        lista_x.append(x)
        x0 = x
    Tabla = pd.DataFrame({"Iteraciones": lista_x, "Errores": lista_e})
    pd.set_option('display.precision', 10)
    return Tabla

## Ejemplo 

Usar el método de Newton para obtener soluciones con una tolerancia de $10^{-6}$ para la ecuación 
$\ln (x-1)+\cos (x-1)=0$ usando una estimación inicial $x_0=1.5$

In [20]:
#Introducir f
f = lambda x: math.log(x-1)+math.cos(x-1)

#Indroducir df = 1/(x-1)-sen(x-1)
df = lambda x: 1/(x-1)-math.sin(x-1)

x0 = 1.5
tol = 1e-6
maxiter = 30

#Obtenemos los resultados
x,iters,error = Newton(f,df,x0,tol,maxiter)

In [21]:
print("La solución a la ecuación es x = %s" %x)
print("El número de iteraciones fue de %s" %iters)
print("El error que se tuvo fue %s" %error)

La solución a la ecuación es x = 1.3977484759580519
El número de iteraciones fue de 4
El error que se tuvo fue 6.389668094630707e-07

In [22]:
NewtonTabla(f,df,x0,tol,maxiter)

    Iteraciones       Errores
0  1.3787067743  0.1212932257
1  1.3971358133  0.0184290390
2  1.3977478370  0.0006120237
3  1.3977484760  0.0000006390

## Ejemplo 

Resolver la ecuación $$e^x+2^{-x}+2 \cos x-6=0$$
usando el método de Newton con $x_0=1.5$ y una tolerancia de $10^{-5}$

In [23]:
#Introducir f
f = lambda x: math.exp(x)+2**(-x)+2*math.cos(x)-6

#Introducir la derivada df = e^x-2^(-x)ln(2)-2sin(x)
df = lambda x: math.exp(x)-2**(-x)*math.log(2)-2*math.sin(x)

x0 = 1.5 #Estimación inicial
tol = 1e-5 #Tolerancia
maxiter = 30

x,iters,error = Newton(f,df,x0,tol,maxiter)

In [24]:
print("La solución a la ecuación es x = %s" %x)
print("El número de iteraciones fue de %s" %iters)
print("El error que se tuvo fue %s" %error)

La solución a la ecuación es x = 1.829383601933849
El número de iteraciones fue de 5
El error que se tuvo fue 1.2560317008691868e-08

In [25]:
NewtonTabla(f,df,x0,tol,maxiter)

    Iteraciones       Errores
0  1.9564897211  0.4564897211
1  1.8415330610  0.1149566601
2  1.8295060132  0.0120270478
3  1.8293836145  0.0001223987
4  1.8293836019  0.0000000126

## Ejemplo

La suma de dos números es $20$. Si a cada uno se le agrega a su raíz cuadrada el producto de las dos sumas es 155.55. Determinar los dos números con un tolerancia de $10^{-6}$.

In [26]:
#Introducir f

f = lambda x: (x+math.sqrt(x))*(20-x+math.sqrt(20-x))-155.55

#Introducir df
df = lambda x: (x+math.sqrt(x))*(-1-1/2*(20-x)**(-1/2))+(20-x+math.sqrt(20-x))*(1-1/2*x**(-1/2))

#Estimación inicial
x0 = 10
tol = 1e-6
maxiter = 30

x,iters,error = Newton(f,df,x0,tol,maxiter)

In [27]:
print("La solución a la ecuación es x = %s" %x)
print("El número de iteraciones fue de %s" %iters)
print("El error que se tuvo fue %s" %error)

La solución a la ecuación es x = 13.487151346305708
El número de iteraciones fue de 11
El error que se tuvo fue 2.9990205341334786e-07

In [28]:
NewtonTabla(f,df,x0,tol,maxiter)

      Iteraciones       Errores
0   14.2514110418  4.2514110418
1   13.6601675273  0.5912435145
2   13.5221523138  0.1380152134
3   13.4940151978  0.0281371160
4   13.4884884546  0.0055267432
5   13.4874114325  0.0010770221
6   13.4872018768  0.0002095557
7   13.4871611160  0.0000407607
8   13.4871531882  0.0000079279
9   13.4871516462  0.0000015419
10  13.4871513463  0.0000002999

In [29]:
#Encontramos y
y = 20-x
print("El otro número buscado es %s" %y)

El otro número buscado es 6.512848653694292

In [30]:
x+y

20.0

In [31]:
(x+math.sqrt(x))*(y+math.sqrt(y))

155.5499992597451

## Ejemplo

Al dejar caer un objeto con una masa $m$ desde una altura $s_0$ la altura se encuentra con la fórmula
$$s(t)=s_0-\dfrac{mg}{k}t+\dfrac{m^2g}{k^2}(1-e^{-kt/m})$$
donde $g=32.17$, $s_0=300$, $m=0.25$ y $k=0.1$. Obtener con una tolerancia de $10^{-5}$ el tiempo que tarda el objeto en tocar el suelo.

In [33]:
f = lambda t: 300-80.425*t+201.0625*(1-math.exp(-0.4*t))

df = lambda t: -80.425+80.425*math.exp(-0.4*t)

x0 = 5
tol = 1e-5
maxiter = 30

x,iters,error = Newton(f,df,x0,tol,maxiter)

print(f"La solución a la ecuación es x = {x}")
print("El número de iteraciones fue de %s" %iters)
print("El error que se tuvo fue %s" %error)

La solución a la ecuación es x = 6.003726308758784
El número de iteraciones fue de 4
El error que se tuvo fue 4.581224288813246e-12