<table style="width:100%; font-size:11pt; border-collapse:collapse">
    <tr>
        <td colspan="2"
            style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   text-align:center;
                   font-weight:bold;
                   padding:8px;">
            Universidad de Oriente
        </td>
    </tr>
    <tr>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
                            Métodos Numéricos
        </td>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
            Clase 18 - Método de Newton
        </td>
    </tr>
    <tr>
 

</table>

In [90]:
import math
import pandas as pd

In [91]:
def Newton(f,df,x0,tol,maxiter):
    iters = 0
    error = tol+1

    while error>tol and iters<=maxiter:
        x = x0-f(x0)/df(x0)
        error = math.fabs(x-x0)
        iters = iters+1
        x0 = x
    return [x, iters, error]

In [92]:
def NewtonTabla(f,df,x0,tol,maxiter):
    iters = 0
    error = tol+1
    lista_e = list(); lista_x = list()
    
    while error>tol and iters<=maxiter:
        x = x0-f(x0)/df(x0)
        error = math.fabs(x-x0)
        iters = iters+1
        lista_e.append(error)
        lista_x.append(x)
        x0 = x
    Tabla = pd.DataFrame({"Iteraciones": lista_x, "Errores": lista_e})
    pd.set_option('display.precision', 10)
    return Tabla

## Ejemplo

Usar el método de Newton para resolver la ecuación $x^3-3x-5=0$ con una tolerancia de $10^{-6}$ con una estimación inicial de $x_0=2$

In [93]:
#Introducir f
f = lambda x: x**3-3*x-5

#Introducir la derivada
df = lambda x: 3*x**2-3
x0 = 2
tol = 1e-6
maxiter = 30

In [94]:
NewtonTabla(f,df,x0,tol,maxiter)

    Iteraciones           Errores
0  2.3333333333  3.3333333333e-01
1  2.2805555556  5.2777777778e-02
2  2.2790200680  1.5354876055e-03
3  2.2790187862  1.2817826032e-06
4  2.2790187862  8.9261931180e-13

In [95]:
#Introducir f
f = lambda x: math.log(x-1)+math.cos(x-1)
#Introducir la derivada
df = lambda x: 1/(x-1)-math.sin(x-1)
x0 = 1.5
tol = 1e-6
maxiter = 30

x, iters, error = Newton(f,df,x0,tol, maxiter)

In [96]:
print(f"La solución a la ecuación es x = {x}")
print(f"El número de la iteraciones fue = {iters}")
print(f"El error que obtuvo fue = {error}")

La solución a la ecuación es x = 1.3977484759580519
El número de la iteraciones fue = 4
El error que obtuvo fue = 6.389668094630707e-07

In [97]:
NewtonTabla(f,df,x0,tol,maxiter)

    Iteraciones       Errores
0  1.3787067743  0.1212932257
1  1.3971358133  0.0184290390
2  1.3977478370  0.0006120237
3  1.3977484760  0.0000006390

# Ejemplo

Resolver la ecuación

$e^x+2^{-x}+2cosx-6=0$

In [98]:
# introducir f
f = lambda x: math.exp(x)+2**(-x)+2*math.cos(x)-6

# introducir la derivada = e^x-2(-x)ln(2)2sin(x)

df = lambda x: math.exp(x)-2**(-x)*math.log(2)-2*math.sin(x)
x0 = 1.5
tol = 1e-6
maxiter = 30

x, iters, error = Newton(f,df,x0,tol, maxiter)

print(f"La solución a la ecuación es x = {x}")
print(f"El número de la iteraciones fue = {iters}")
print(f"El error que obtuvo fue = {error}")

La solución a la ecuación es x = 1.829383601933849
El número de la iteraciones fue = 5
El error que obtuvo fue = 1.2560317008691868e-08

In [99]:
NewtonTabla(f,df,x0,tol,maxiter)

    Iteraciones       Errores
0  1.9564897211  0.4564897211
1  1.8415330610  0.1149566601
2  1.8295060132  0.0120270478
3  1.8293836145  0.0001223987
4  1.8293836019  0.0000000126

In [100]:
f = lambda x: (x+math.sqrt(x))*(20-x+math.sqrt(20-x))-155.55

df = lambda x: (x+math.sqrt(x))*(-1-1/2*(20-x)**(-1/2))+(20-x+math.sqrt(20-x))*(1-1/2*x**(-1/2))

x0 = 10
tol = 1e-6
maxiter = 30

x, iters, error = Newton(f,df,x0,tol, maxiter)

print(f"La solución a la ecuación es x = {x}")
print(f"El número de la iteraciones fue = {iters}")
print(f"El error que obtuvo fue = {error}")

La solución a la ecuación es x = 13.487151346305708
El número de la iteraciones fue = 11
El error que obtuvo fue = 2.9990205341334786e-07

In [101]:
NewtonTabla(f,df,x0,tol,maxiter)

      Iteraciones       Errores
0   14.2514110418  4.2514110418
1   13.6601675273  0.5912435145
2   13.5221523138  0.1380152134
3   13.4940151978  0.0281371160
4   13.4884884546  0.0055267432
5   13.4874114325  0.0010770221
6   13.4872018768  0.0002095557
7   13.4871611160  0.0000407607
8   13.4871531882  0.0000079279
9   13.4871516462  0.0000015419
10  13.4871513463  0.0000002999

In [102]:
y = 20 -x
print(f"El otro número que buscamos es {y}")

El otro número que buscamos es 6.512848653694292